# Thi·∫øt l·∫≠p m√¥i tr∆∞·ªùng build
[build.environment]
  NETLIFY_USE_YARN = "true"
  YARN_VERSION = "1.22.17"
  NODE_VERSION = "20"

# L·ªánh build ch√≠nh v√† th∆∞ m·ª•c output
[build]
  command = "yarn build"
  publish = "dist"
  base = "site" # üëà th√™m d√≤ng n√†y ƒë·ªÉ Netlify build trong th∆∞ m·ª•c 'site'

# C·∫•u h√¨nh khi deploy preview
[context.deploy-preview]
  command = "yarn build:preview"

# Thi·∫øt l·∫≠p khi ch·∫°y dev local (Netlify Dev)
[dev]
  framework = "hugo"
  targetPort = 3000
